name: Deploy app

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update app container
        run: |
          docker exec swbot-app git pull origin main
          docker exec swbot-app npm install --only=production

      - name: Restart app container
        run: |
          docker restart swbot-app
